
// 주요 도시 데이터베이스 (KO <-> EN 매핑)
// RayPersona: 검색 효율을 위해 한글 위주로 정리
const CITY_DATA = [
    { ko: "서울", en: "Seoul", country: "KR" },
    { ko: "인천", en: "Incheon", country: "KR" },
    { ko: "부산", en: "Busan", country: "KR" },
    { ko: "제주", en: "Jeju", country: "KR" },
    { ko: "서귀포", en: "Seogwipo", country: "KR" },
    { ko: "대구", en: "Daegu", country: "KR" },
    { ko: "광주", en: "Gwangju", country: "KR" },
    { ko: "대전", en: "Daejeon", country: "KR" },
    { ko: "울산", en: "Ulsan", country: "KR" },
    { ko: "수원", en: "Suwon", country: "KR" },
    { ko: "용인", en: "Yongin", country: "KR" },
    { ko: "성남", en: "Seongnam", country: "KR" },
    { ko: "도쿄", en: "Tokyo", country: "JP" },
    { ko: "오사카", en: "Osaka", country: "JP" },
    { ko: "교토", en: "Kyoto", country: "JP" },
    { ko: "후쿠오카", en: "Fukuoka", country: "JP" },
    { ko: "삿포로", en: "Sapporo", country: "JP" },
    { ko: "나고야", en: "Nagoya", country: "JP" },
    { ko: "히로시마", en: "Hiroshima", country: "JP" },
    { ko: "오키나와", en: "Okinawa", country: "JP" },
    { ko: "베이징", en: "Beijing", country: "CN" },
    { ko: "상하이", en: "Shanghai", country: "CN" },
    { ko: "홍콩", en: "Hong Kong", country: "HK" },
    { ko: "타이베이", en: "Taipei", country: "TW" },
    { ko: "방콕", en: "Bangkok", country: "TH" },
    { ko: "다낭", en: "Da Nang", country: "VN" },
    { ko: "하노이", en: "Hanoi", country: "VN" },
    { ko: "호치민", en: "Ho Chi Minh City", country: "VN" },
    { ko: "싱가포르", en: "Singapore", country: "SG" },
    { ko: "쿠알라룸푸르", en: "Kuala Lumpur", country: "MY" },
    { ko: "세부", en: "Cebu", country: "PH" },
    { ko: "마닐라", en: "Manila", country: "PH" },
    { ko: "뉴욕", en: "New York", country: "US" },
    { ko: "로스앤젤레스", en: "Los Angeles", country: "US" },
    { ko: "샌프란시스코", en: "San Francisco", country: "US" },
    { ko: "시카고", en: "Chicago", country: "US" },
    { ko: "런던", en: "London", country: "GB" },
    { ko: "파리", en: "Paris", country: "FR" },
    { ko: "베를린", en: "Berlin", country: "DE" },
    { ko: "로마", en: "Rome", country: "IT" },
    { ko: "마드리드", en: "Madrid", country: "ES" },
    { ko: "시드니", en: "Sydney", country: "AU" },
    { ko: "멜버른", en: "Melbourne", country: "AU" }
];
