const langData = {
    ko: {
        // Global
        pageTitle: "제주 그룹 - 모든 여행을 제주그룹 하나로",
        login: "로그인",
        signup: "회원가입",
        customerCenter: "고객센터",
        reservationCheck: "예약 확인",
        navAir: "제주에어",
        navHotel: "제주 스테이",
        navLife: "전 세계 한 달 살기",
        navActivity: "즐길 거리",
        navRentCar: "제주 렌트카",
        navMembership: "멤버십",
        langToggle: "English",
        footerCompany: "(주)제주 그룹",
        footerCEO: "대표이사: 김이배",
        footerBizNum: "사업자등록번호: 616-81-50527",
        footerSaleNum: "통신판매업신고: 제주 2006-125호",
        footerHosting: "호스팅 사업자: AWS",
        footerAddr: "주소: 제주특별자치도 제주시 신대로 64 (연동, 건설공제회관 3층)",
        footerCs: "고객센터: 1599-1500 (09:00 ~ 19:00)",
        footerCsEmail: "고객 문의: jejugroup.help@jejugroup.net",
        footerPartnerEmail: "제휴 문의: partnership@jejugroup.net",
        footerCopyright: "Copyright ⓒ Jeju Group. All Rights Reserved.",

        // Main Page (Index)
        heroTitle: "모든 여행의 시작과 끝, 제주그룹이 함께합니다.",
        heroSubtitle: "하늘, 머물음, 그리고 드라이브. 모든 여행을 제주그룹 한 곳에서.",
        scrollDown: "Scroll Down",
        airTag: "제주에어",
        airTitle: "가장 빠르고 편안한 하늘길",
        airDesc: "제주에어는 합리적인 운임으로 최고의 서비스를 제공합니다. 국내외 주요 노선을 운항하며, 편안한 객실 환경과 친절한 승무원 서비스로 당신의 여행을 더욱 특별하게 만들어드립니다.",
        airButton: "항공권 예약하기",
        airFeature1: "합리적인 운임",
        airFeature2: "편안한 객실",
        airFeature3: "친절한 서비스",
        hotelTag: "제주호텔",
        hotelTitle: "자연을 품은 프리미엄 휴식처",
        hotelDesc: "제주호텔은 아름다운 자연 속에서 프리미엄한 휴식을 제공합니다. 현대적인 시설과 전통의 따뜻함이 어우러진 객실에서 잊을 수 없는 밤을 경험하세요.",
        hotelButton: "객실 둘러보기",
        hotelFeature1: "프리미엄 객실",
        hotelFeature2: "자연 친화적 설계",
        hotelFeature3: "최고의 서비스",
        rentCarTag: "제주렌트카",
        rentCarTitle: "완벽한 드라이빙을 위한 최신형 차량",
        rentCarDesc: "제주렌트카는 최신형 차량으로 완벽한 드라이빙 경험을 제공합니다. 여행지의 도로를 자유롭게 누비며, 당신만의 특별한 여행을 만들어보세요. 24시간 고객지원으로 안전한 여행을 보장합니다.",
        rentCarButton: "차량 예약하기",
        rentCarFeature1: "최신형 차량",
        rentCarFeature2: "합리적인 가격",
        rentCarFeature3: "24시간 지원",
        membershipTitle: "멤버십",
        membershipSubtitle: "제주 여행의 모든 순간을 더욱 특별하게",
        membershipNotice1: "모든 멤버십은 언제든지 취소할 수 있습니다.",
        membershipNotice2: "추가 혜택과 이벤트는 <strong>제주 그룹 앱</strong>에서 확인하세요.",
        appStrong: "제주 그룹 앱",
        silverTitle: "실버 멤버",
        silverPrice: "월 <span>29,900</span>원",
        joinButton: "가입하기",
        silverBenefit1: "✓ 항공권 5% 할인",
        silverBenefit2: "✓ 호텔 예약 10% 할인",
        silverBenefit3: "✓ 렌트카 기본료 할인",
        silverBenefit4: "✓ 우선 고객 지원",
        popular: "인기",
        goldTitle: "골드 멤버",
        goldPrice: "월 <span>49,900</span>원",
        goldBenefit1: "✓ 항공권 10% 할인",
        goldBenefit2: "✓ 호텔 예약 15% 할인",
        goldBenefit3: "✓ 렌트카 기본료 20% 할인",
        goldBenefit4: "✓ 무료 공항 라운지",
        goldBenefit5: "✓ 우선 예약 서비스",
        platinumTitle: "플래티넘 멤버",
        platinumPrice: "월 <span>79,900</span>원",
        platinumBenefit1: "✓ 항공권 15% 할인",
        platinumBenefit2: "✓ 호텔 예약 20% 할인",
        platinumBenefit3: "✓ 렌트카 기본료 30% 할인",
        platinumBenefit4: "✓ VIP 라운지 이용",
        platinumBenefit5: "✓ 전담 컨시어지 서비스",
        platinumBenefit6: "✓ 무료 취소 정책",

        // Login Page
        loginDesc: "모든 여행을 제주그룹 하나로",
        emailLabel: "이메일",
        emailPlaceholder: "example@jejugroup.com",
        passwordLabel: "비밀번호",
        passwordPlaceholder: "비밀번호 입력",
        loginButton: "로그인",
        findIdPw: "아이디/비밀번호 찾기",

        // Signup Page
        signupTitle: "회원가입",
        signupDesc: "모든 여행을 제주그룹 하나로",
        basicInfo: "기본 정보",
        nameLabel: "이름",
        namePlaceholder: "홍길동",
        phoneLabel: "휴대폰 번호",
        phonePlaceholder: "010-0000-0000",
        verifyBtn: "인증",
        accountInfo: "계정 정보",
        passwordStrength: "8자 이상, 영문, 숫자, 특수문자를 포함해야 합니다.",
        passwordConfirmLabel: "비밀번호 확인",
        passwordConfirmPlaceholder: "비밀번호 재입력",
        personalInfo: "개인 정보",
        birthdateLabel: "생년월일",
        genderLabel: "성별",
        male: "남성",
        female: "여성",
        other: "기타",
        addressLabel: "주소",
        addressPlaceholder: "주소 입력",
        termsAgree: "약관 동의",
        agreeTerms: "이용약관에 동의합니다.",
        agreePrivacy: "개인정보 수집 및 이용에 동의합니다.",
        agreeMarketing: "마케팅 정보 수신에 동의합니다.",
        viewTerms: "약관 보기",
        signupButton: "회원가입",
        haveAccount: "이미 계정이 있으신가요?",

        // Reservation Check Page
        resCheckTitle: "비회원 예약 조회",
        resCheckDesc: "예약 번호와 정보를 입력하여 예약을 확인하세요.",
        resNumLabel: "예약 번호",
        resNumPlaceholder: "예약 번호를 입력하세요",
        resEmailPlaceholder: "예약 시 사용한 이메일",
        checkButton: "조회하기",
        isMember: "회원이신가요?",
        loginCheckLink: "로그인하여 확인하기",

        // Hotel Page
        hotelPageTitle: "JEJU STAY | 전 세계 호텔 예약",
        heroSubtitleTop: "전 세계 200만 개 이상의 호텔, 리조트, 펜션을 최저가로 예약",
        tabHotel: "호텔 & 리조트",
        tabPension: "펜션 & 풀빌라",
        tabActivity: "즐길거리",
        destLabel: "여행지",
        dateLabel: "여행 일정",
        guestLabel: "여행자",
        destPlaceholder: "어디로 떠나시나요?",
        checkIn: "체크인",
        checkOut: "체크아웃",
        dateSelect: "날짜 선택",
        guestAdult: "성인",
        guestChild: "아동",
        guestRoom: "객실",
        searchBtn: "검색",
        promoTitle1: "제주항공 탑승객 인증 시<br>전 세계 호텔 <strong>7% 추가 할인</strong>",
        promoDesc1: "제주항공 예약 확인서를 업로드하고 특별 할인을 받으세요",
        promoLink1: "자세히 보기",
        promoTitle2: "리프레시 포인트로<br>호텔 결제 가능",
        promoLink2: "포인트 사용하기",
        promoTitle3: "숙소 + 렌터카<br>패키지 최대 15% 할인",
        promoLink3: "패키지 보기",
        destTitle: "한국인이 사랑하는 인기 여행지",
        destSubtitle: "지금 가장 핫한 여행지에서 특별한 숙소를 만나보세요",
        dealsTitle: "이달의 특가 호텔",
        dealsSubtitle: "JJ 멤버 전용 특별 할인가로 만나보세요",
        moreHotels: "더 많은 특가 호텔 보기",
        
        // FAB
        fabCurrencyLabel: "화폐 변경",
        fabWishlistLabel: "위시리스트",
        fabChatbotLabel: "AI 챗봇",
        
        // Header & Mobile Nav (Common)

        navResCheck: "예약 확인",
        navLogin: "로그인",
        navCs: "고객센터",
        mobileNavHotel: "숙소 예약",
        mobileNavLife: "한 달 살기",
        mobileNavActivity: "즐길 거리",
        
        // New Nav Items
        navEsim: "eSIM",
        navGuide: "여행 가이드",
        navTips: "여행 일정 팁",
        mobileNavEsim: "eSIM",
        mobileNavGuide: "여행 가이드",
        mobileNavTips: "여행 일정 팁",

        // Hotel Page Additional
        destKr: "대한민국 내 여행지",
        destOverseas: "해외 여행지",
        destDescSeoul: "쇼핑, 레스토랑",
        destDescBusan: "해변, 레스토랑",
        destDescJeju: "자연경관, 해변",

        // Calendar & Search Common
        dateSelect: "날짜 선택",
        checkIn: "체크인",
        checkOut: "체크아웃",
        btnReset: "초기화",
        btnConfirm: "확인",
        
        // Calendar Popup
        calTitle: "캘린더",
        calFlexible: "날짜 미정",
        calFlexTitle: "투숙 기간은 얼마나 되시나요?",
        calFlex3: "3박",
        calFlex7: "1주일",
        calFlex30: "1개월",
        
        // Guest Popup
        guestRooms: "객실",
        guestAdults: "성인",
        guestAdultsDesc: "18세 이상",
        guestChildren: "아동",
        guestChildrenDesc: "0 - 17세",
        
        // Hotel Destination Descriptions
        descShoppingDining: "쇼핑, 레스토랑",
        descShoppingSightseeing: "쇼핑, 관광",
        descSightseeingBeach: "관광, 해변",
        descBeachResort: "해변, 리조트",
        descSnowBeer: "설경, 맥주",
        descNightModern: "야경, 현대미",
        descEuropeBeer: "유럽풍, 맥주",
        descArtRomantic: "예술, 낭만",
        descHistoryCulture: "역사, 문화",
        descRuinsDining: "유적, 미식",
        descArchiPassion: "건축, 열정",
        descCityShopping: "도시, 쇼핑",
        descRelaxSurf: "휴양, 서핑",
        descNightlife: "나이트라이프",
        descFamilyRelax: "가족 휴양",
        descDivingSea: "다이빙, 바다",
        descYogaNature: "요가, 자연",
        descCityLuxury: "도시, 럭셔리",

        // Hotel Names & Locations (Static Data)
        hotelNameGrandHyatt: "그랜드 하얏트 제주",
        hotelLocGrandHyatt: "제주시 노형동 · 해변까지 도보 5분",
        hotelNameOsakaRitz: "오사카 리츠칼튼",
        hotelLocOsakaRitz: "오사카 키타구 · 우메다역 도보 3분",
        hotelNameDanangInter: "다낭 인터컨티넨탈 선 페닌슐라",
        hotelLocDanangInter: "다낭 손트라 · 프라이빗 비치",
        hotelNameBangkokMandarin: "방콕 만다린 오리엔탈",
        hotelLocBangkokMandarin: "방콕 차오프라야강 · 리버뷰",
        
        // Hotel Amenities & Review
        amenityWifi: "무료 와이파이",
        amenityPool: "수영장",
        amenityBreakfast: "조식 포함",
        amenityFitness: "피트니스",
        amenitySpa: "스파",
        amenityInfinity: "인피니티 풀",
        amenityShuttle: "셔틀보트",
        reviewExcellent: "최고",
        reviewGreat: "훌륭함",
        reviewSuffix: "개",
        pricePerNight: "1박 요금",
        priceTaxIncl: "세금 포함",
        priceTaxIncl: "세금 포함",
        discountOff: "할인",

        // Destination Names & Counts
        destNameSeoul: "서울",
        destNameIncheon: "인천",
        destNameBusan: "부산",
        destNameSokcho: "속초",
        destNameGyeongju: "경주",
        destNameFukuoka: "후쿠오카",
        destNameJeju: "제주도",
        destNameOsaka: "오사카",
        destNameDanang: "다낭",
        destNameBangkok: "방콕",
        destNameTokyo: "도쿄",
        destNameSingapore: "싱가포르",
        destCountJeju: "숙소 3,240개",
        destCountOsaka: "숙소 5,120개",
        destCountDanang: "숙소 2,890개",
        destCountBangkok: "숙소 8,450개",
        destCountTokyo: "숙소 7,320개",
        destCountSingapore: "숙소 1,890개",
        badgeSpecial: "특가",
        descTourism: "관광",
        descBeachDining: "해변, 레스토랑",
        descCultureReligion: "문화, 종교 관심 활동",


        // Activity Cards (Static Data)
        actTitleCebu: "[세부] 오슬롭 고래상어 투어 + 캐녀닝 (단독/조인)",
        actLocCebu: "세부 · 워터스포츠",
        actTitleBangkok: "[방콕] 렛츠 릴렉스 스파 (지점 선택 가능)",
        actLocBangkok: "방콕 · 마사지",
        actTitleVenice: "[베니스] 곤돌라 탑승권 + 오디오 가이드",
        actLocVenice: "베니스 · 투어",
        actTitleHawaii: "[와이키키] 서핑 입문 강습 (한국인 강사)",
        actLocHawaii: "하와이 · 서핑",
        actBenefitPhoto: "사진 촬영 무료",
        actBenefitFast: "빠른 입장",

        // Life Page
        lifeHeroSubtitle: "제주항공으로 떠나는 전 세계 한 달 살기,<br><strong>숙소부터 렌터카까지 가장 완벽한 생태계</strong>",
        lifeSearchSummaryTitle: "어디서 살아볼까요?",
        lifeSearchSummaryDesc: "지역, 날짜, 필수 옵션 선택",
        lifeDestPlaceholder: "전 세계 어디서 살아볼까요?",
        lifeDestJapanChina: "일본 / 중국",
        lifeDestSEAsia: "동남아시아",
        lifeDestEurope: "유럽 / 미주",
        
        lifeStayWarning: "* 최소 14박 이상 선택해주세요",
        lifeAmenityLabel: "필수 옵션",
        lifeAmenityPlaceholder: "주방, 세탁기 등",
        lifeOptKitchen: "풀옵션 주방",
        lifeOptWasher: "세탁기/건조기",
        lifeOptDesk: "업무용 데스크",
        lifeOptParking: "전용 주차장",
        lifeSearchBtn: "장기 숙소 검색하기",
        
        lifeSynergyTitle: "전 세계 어디든 제주항공 X 모빌리티 혜택",
        lifeSynergyDesc: "항공권 결합 시 리프레시 포인트 2배 적립 + 해외 렌터카 50% 할인!",
        lifeSynergyLink: "제주 유니버스 혜택 보기",
        
        lifeCurationTitle: "당신의 라이프스타일에 맞는 집",
        lifeCurationDesc: "한 달 살기, 목적에 따라 큐레이션된 숙소를 만나보세요",
        lifeCurChiangmaiDesc: "디지털 노마드의 성지,<br>완벽한 업무 환경과 저렴한 물가",
        lifeCurLisbonDesc: "오래된 골목과 파두가 흐르는<br>낭만적인 유럽의 일상",
        lifeCurBaliDesc: "요가와 명상으로 채우는 하루,<br>논뷰가 펼쳐지는 힐링 스테이",
        
        lifeMagTag: "Global Pick",
        lifeMagTitle: "치앙마이, 느리게 걷는<br>여행자의 아침",
        lifeMagDesc: "매일 아침 눈을 뜨면 펼쳐지는 도이수텝의 능선, 혹은 님만해민의 활기.<br>호텔에서는 느낄 수 없는 '현지인' 같은 편안함을 선물합니다.<br>단골 카페에서 시작하는 업무와 야시장에서 즐기는 저녁까지,<br>진정한 노마드의 삶을 경험해보세요.",
        lifeMagLink: "매거진 더 보기",
        
        lifeInfraTitle: "편리한 주변 인프라",
        lifeInfraDesc: "오래 머물수록 중요한 생활 편의시설을 확인하세요",
        lifeInfraMart: "대형 마트",
        lifeInfraHosp: "종합 병원",
        lifeInfraBus: "대중 교통",
        lifeInfraWalk10: "도보 10분",
        lifeInfraCar15: "차량 15분",
        lifeInfraWalk5: "도보 5분",
        
        lifeConnectTitle: "Seamless Journey",
        lifeConnectTag: "제주항공 고객 전용",
        lifeConArr: "공항 도착",
        lifeConShuttle: "셔틀 15분",
        lifeConPick: "픽업/이동",
        lifeConMove: "이동 35분",
        lifeConCheckin: "숙소 체크인",
        lifeConCheckinDesc: "도어락 비밀번호 전송",
        
        lifeDealTitle: "장기 체류 추천 숙소",
        lifeDealDesc: "14박 이상 예약 시 적용되는 특별한 혜택가",
        
        lifeReviewTitle: "한 달 살기 리얼 후기",
        lifeReviewDesc: "먼저 다녀온 입주민들의 생생한 기록",
        lifeReviewText1: "\"아침엔 도이수텝을 보며 조깅하고, 낮에는 공유 오피스에서 집중해서 일했어요. 치앙마이 라이프는 정말 꿈만 같았습니다.\"",

        // Selection Standards
        stdTitle: "제주스테이가 검증한 '살기 좋은 집'의 기준",
        stdSubtitle: "전 세계 200만 개 숙소 중 장기 체류에 최적화된 곳만 선별했습니다.",
        stdItem1Title: "생활 필수 가전 완비",
        stdItem1Desc: "주방 도구, 세탁기, 초고속 와이파이 등 장기 투숙 시 별도 구매가 필요 없는 '풀 퍼니시드' 숙소만 입점합니다.",
        stdItem2Title: "24시간 안전 검증",
        stdItem2Desc: "치안이 확보된 지역인지, 건물 내 보안 시스템이 작동하는지 현지 파트너가 직접 방문하여 확인합니다.",
        stdItem3Title: "장기 예약 전용 특가",
        stdItem3Desc: "14박 이상 예약 시 일반 1박 요금 대비 평균 25~40% 저렴한 'Long-Stay' 전용 레이트를 보장합니다.",
        stdItem4Title: "유연한 취소 정책",
        stdItem4Desc: "일정 변경이 잦은 장기 여행자를 위해, 입주 7일 전까지는 유연하게 취소 및 변경이 가능한 숙소를 우선 노출합니다.",

        // Long Stay Promos & Membership
        lifeMemTitle: "Long Stay 멤버십 혜택",
        promoLuggageTitle: "위탁 수하물<br>10kg 추가 증정",
        promoLuggageDesc: "짐이 많은 장기 여행도 걱정 없이,<br>제주항공 이용 시 혜택 제공",
        promoCardTitle: "로컬 라이프<br>멤버십 카드",
        promoCardDesc: "현지인 맛집, 카페, 렌터카까지<br>최대 20% 제휴 할인",
        promoGuideTitle: "한 달 살기<br>가이드북 제공",
        promoGuideDesc: "쓰레기 배출일부터 근처 인프라 정보까지<br>생활 필수 정보 수록",


        // Activities Page
        actHeroTitle: "여행의 완성을 넘어,<br>제주항공과의 완벽한 연결",
        actHeroSubtitle: "탑승객 전용 혜택으로 만나는 로컬의 모든 경험",
        actSearchPlaceholder: "어디로 떠나시나요? 도시나 액티비티를 검색해보세요",
        actSearchBtn: "검색",
        
        filterAll: "전체",
        filterTour: "투어/가이드",
        filterTicket: "티켓/입장권",
        filterWater: "워터스포츠",
        filterSpa: "스파/힐링",
        filterFood: "맛집/다이닝",

        authTitle: "제주항공 탑승객 인증",
        authDesc: "항공권번호를 인증하고 <strong>최대 50% 추가 할인</strong> 혜택을 받으세요.",
        authBtn: "인증하고 혜택받기",
        
        authModalTitle: "제주항공 탑승권 인증",
        authModalDesc: "예약번호(6자리)와 탑승일을 입력해주세요.",
        authLabelRes: "예약번호",
        authLabelDate: "탑승일",
        authSubmit: "혜택 적용하기",
        
        actSectionTitle: "추천 액티비티",
        actInstant: "즉시 확정",
        actBenefit: "제주 유니버스 혜택",
        actPoint2x: "포인트 2배",

        // Customer Center
        csHeroTitle: "무엇을 도와드릴까요?",
        csHeroSubtitle: "궁금한 점을 검색하거나 아래 자주 묻는 질문을 확인하세요.",
        csSearchPlaceholder: "검색어를 입력해주세요 (예: 수하물, 환불, 예약변경)",
        csTabAll: "자주 묻는 질문",
        csTabRes: "항공 예약",
        csTabHotel: "호텔/숙박",
        csTabBaggage: "수하물",
        csTabMembership: "멤버십",
        
        faqCatRes: "[항공 예약]",
        faqQ1: "예약 변경 및 취소 수수료는 얼마인가요?",
        faqA1: "예약 변경 및 취소 수수료는 구매하신 항공권의 운임 규정에 따라 다릅니다. 특가 운임의 경우 환불이 불가하거나 높은 수수료가 부과될 수 있습니다. 정확한 수수료는 [마이페이지 > 예약 조회]에서 확인하실 수 있습니다.",
        
        faqCatBag: "[수하물]",
        faqQ2: "무료 위탁 수하물 허용량은 어떻게 되나요?",
        faqA2: "국제선의 경우 FLY 운임은 15kg, FLYBAG 운임은 15kg, BIZ LITE 운임은 30kg까지 무료로 위탁하실 수 있습니다. 기내 휴대 수하물은 10kg 이내 1개 가방만 허용됩니다. (노선 및 회원 등급에 따라 상이할 수 있습니다.)",
        
        faqCatMem: "[멤버십]",
        faqQ3: "제주항공 리프레시 포인트 유효기간은 언제까지인가요?",
        faqA3: "적립된 리프레시 포인트의 유효기간은 적립일로부터 3년입니다. 이벤트나 프로모션으로 적립된 포인트는 별도의 유효기간이 적용될 수 있으니 [마이페이지 > 포인트 조회]에서 확인해 주시기 바랍니다.",
        
        faqCatHotel: "[호텔/숙박]",
        faqQ4: "호텔 예약 시 포인트 사용이 가능한가요?",
        faqA4: "네, 제주 스테이(Jeju Stay) 제휴 호텔 예약 시 보유하신 리프레시 포인트를 현금처럼 사용하여 결제하실 수 있습니다. 1포인트는 1원의 가치를 가집니다.",
        
        faqQ5: "임산부 탑승 규정이 궁금합니다.",
        faqA5: "임신 32주 미만의 임산부는 의사 소견 없이 자유롭게 항공 여행이 가능합니다. 32주 이상 36주 미만의 경우 의사 소견서가 필요하며, 37주 이상(다태아 33주 이상)의 경우 탑승이 제한될 수 있습니다.",

        inquiryTitle: "더 궁금한 점이 있으신가요?",
        inquiryDesc: "AI 챗봇이 24시간 언제든지 빠르고 정확하게 답변해 드립니다.",
        inquiryBtn: "1:1 채팅 문의하기",

        // Long Stay Card Labels (Moved)
        lifeDailySave: "1박 대비 절약",
        lifePerNightMsg: "1박 환산 시 약",
        lifeTotal30: "30박 세금포함 총액",
        lifePerNightAvg: "1박 평균",
        lifeUtilityIncl: "공과금 포함",
        lifeMemberDiscount: "제주항공 회원 추가 할인 적용",
        lifeTaxServiceIncl: "세금 및 봉사료 포함",


    },
    en: {
        // Global
        pageTitle: "Jeju Group - All Your Travels, One Place: Jeju Group",
        login: "Login",
        signup: "Sign Up",
        customerCenter: "Support",
        reservationCheck: "My Booking",
        navAir: "Jeju Air",
        navHotel: "Jeju Stay",
        navLife: "Long Stay",
        navActivity: "Activities",
        navRentCar: "Jeju Rent-a-Car",
        navMembership: "Membership",
        langToggle: "한국어",
        footerCompany: "Jeju Group Inc.",
        footerCEO: "CEO: Kim Lee-bae",
        footerBizNum: "Business Registration No: 616-81-50527",
        footerSaleNum: "E-commerce Permit: Jeju 2006-125",
        footerHosting: "Hosting Provider: AWS",
        footerAddr: "Address: 3F, 64 Sindae-ro, Jeju-si, Jeju-do, Republic of Korea",
        footerCs: "Customer Service: 1599-1500 (09:00 ~ 19:00)",
        footerCsEmail: "Support: jejugroup.help@jejugroup.net",
        footerPartnerEmail: "Partnerships: partnership@jejugroup.net",
        footerCopyright: "Copyright ⓒ Jeju Group. All Rights Reserved.",

        // Main Page (Index)
        heroTitle: "From Start to Finish, Jeju Group is With You.",
        heroSubtitle: "Sky, Stay, and Drive. All Your Travels in One Place, Jeju Group.",
        scrollDown: "Scroll Down",
        airTag: "Jeju Air",
        airTitle: "The Fastest, Most Comfortable Skyway",
        airDesc: "Jeju Air offers top-tier service at reasonable fares. We operate major domestic and international routes, making your journey special with a comfortable cabin and friendly crew.",
        airButton: "Book a Flight",
        airFeature1: "Reasonable Fares",
        airFeature2: "Comfortable Cabin",
        airFeature3: "Friendly Service",
        hotelTag: "Jeju Hotel",
        hotelTitle: "Premium Relaxation in Nature's Embrace",
        hotelDesc: "Jeju Hotel provides a premium retreat in beautiful nature. Experience an unforgettable night in rooms where modern facilities meet traditional warmth.",
        hotelButton: "Explore Rooms",
        hotelFeature1: "Premium Rooms",
        hotelFeature2: "Eco-friendly Design",
        hotelFeature3: "Best Service",
        rentCarTag: "Jeju Rent-a-Car",
        rentCarTitle: "Latest Vehicles for a Perfect Drive",
        rentCarDesc: "Jeju Rent-a-Car offers a perfect driving experience with the latest vehicles. Freely explore your destination's roads and create your own special trip. We ensure a safe journey with 24-hour customer support.",
        rentCarButton: "Reserve a Car",
        rentCarFeature1: "Latest Vehicles",
        rentCarFeature2: "Reasonable Price",
        rentCarFeature3: "24/7 Support",
        membershipTitle: "Membership",
        membershipSubtitle: "Make every moment of your Jeju trip more special",
        membershipNotice1: "All memberships can be canceled at any time.",
        membershipNotice2: "Check the <strong>Jeju Group App</strong> for additional benefits and events.",
        appStrong: "Jeju Group App",
        silverTitle: "Silver Member",
        silverPrice: "<span>$29.99</span>/month",
        joinButton: "Sign Up",
        silverBenefit1: "✓ 5% off flights",
        silverBenefit2: "✓ 10% off hotel bookings",
        silverBenefit3: "✓ Discount on rental car fees",
        silverBenefit4: "✓ Priority customer support",
        popular: "Best",
        goldTitle: "Gold Member",
        goldPrice: "<span>$49.99</span>/month",
        goldBenefit1: "✓ 10% off flights",
        goldBenefit2: "✓ 15% off hotel bookings",
        goldBenefit3: "✓ 20% off rental car fees",
        goldBenefit4: "✓ Free airport lounge access",
        goldBenefit5: "✓ Priority booking service",
        platinumTitle: "Platinum Member",
        platinumPrice: "<span>$79.99</span>/month",
        platinumBenefit1: "✓ 15% off flights",
        platinumBenefit2: "✓ 20% off hotel bookings",
        platinumBenefit3: "✓ 30% off rental car fees",
        platinumBenefit4: "✓ VIP lounge access",
        platinumBenefit5: "✓ Dedicated concierge service",
        platinumBenefit6: "✓ Free cancellation policy",

        // Login Page
        loginDesc: "All your travels in one place",
        emailLabel: "Email",
        emailPlaceholder: "example@jejugroup.com",
        passwordLabel: "Password",
        passwordPlaceholder: "Enter Password",
        loginButton: "Login",
        findIdPw: "Find ID/Password",

        // Signup Page
        signupTitle: "Sign Up",
        signupDesc: "All your travels in one place",
        basicInfo: "Basic Info",
        nameLabel: "Name",
        namePlaceholder: "John Doe",
        phoneLabel: "Phone Number",
        phonePlaceholder: "010-0000-0000",
        verifyBtn: "Verify",
        accountInfo: "Account Info",
        passwordStrength: "8+ chars, incl. letter, number, special char.",
        passwordConfirmLabel: "Confirm Password",
        passwordConfirmPlaceholder: "Re-enter Password",
        personalInfo: "Personal Info",
        birthdateLabel: "Birthdate",
        genderLabel: "Gender",
        male: "Male",
        female: "Female",
        other: "Other",
        addressLabel: "Address",
        addressPlaceholder: "Enter Address",
        termsAgree: "Terms Agreement",
        agreeTerms: "I agree to the Terms of Service.",
        agreePrivacy: "I agree to the Privacy Policy.",
        agreeMarketing: "I agree to receive marketing info.",
        viewTerms: "View Terms",
        signupButton: "Sign Up",
        haveAccount: "Already have an account?",

        // Reservation Check Page
        resCheckTitle: "Non-Member Booking Check",
        resCheckDesc: "Enter your booking number and info to check your reservation.",
        resNumLabel: "Booking Number",
        resNumPlaceholder: "Enter Booking Number",
        resEmailPlaceholder: "Email used for booking",
        checkButton: "Check Now",
        isMember: "Are you a member?",
        loginCheckLink: "Login to check",

        // Hotel Page
        hotelPageTitle: "JEJU STAY | Worldwide Hotel Booking",
        heroSubtitleTop: "Book over 2 million hotels, resorts, and pensions at the best prices",
        tabHotel: "Hotels & Resorts",
        tabPension: "Pension & Pool Villa",
        tabActivity: "Activities",
        destLabel: "Destination",
        dateLabel: "Dates",
        guestLabel: "Travelers",
        destPlaceholder: "Where are you going?",
        checkIn: "Check-in",
        checkOut: "Check-out",
        dateSelect: "Select Date",
        guestAdult: "Adult",
        guestChild: "Child",
        guestRoom: "Room",
        searchBtn: "Search",
        promoTitle1: "Jeju Air Passenger Auth<br><strong>Extra 7% Off</strong> Worldwide",
        promoDesc1: "Upload your Jeju Air booking confirmation and get special discounts",
        promoLink1: "Learn More",
        promoTitle2: "Pay Hotels with<br>Refresh Points",
        promoLink2: "Use Points",
        promoTitle3: "Stay + Rent-a-Car<br>Package up to 15% Off",
        promoLink3: "View Packages",
        destTitle: "Popular Destinations Koreans Love",
        destSubtitle: "Meet special accommodations in the hottest travel destinations right now",
        dealsTitle: "Monthly Special Deals",
        dealsSubtitle: "Meet special discounts exclusively for JJ members",
        moreHotels: "View More Deals",

        // FAB
        fabCurrencyLabel: "Change Currency",
        fabWishlistLabel: "Wishlist",
        fabChatbotLabel: "AI Chatbot",
        
        // Header & Mobile Nav (Common)

        navResCheck: "My Booking",
        navLogin: "Login",
        navCs: "Support",
        mobileNavHotel: "Hotels",
        mobileNavLife: "Long Stay",
        mobileNavActivity: "Activities",
        
        // New Nav Items
        navEsim: "eSIM",
        navGuide: "Travel Guide",
        navTips: "Travel Tips",
        mobileNavEsim: "eSIM",
        mobileNavGuide: "Travel Guide",
        mobileNavTips: "Travel Tips",

        // Hotel Page Additional
        destKr: "Domestic Destinations",
        destOverseas: "Overseas Destinations",
        destDescSeoul: "Shopping, Dining",
        destDescBusan: "Beaches, Dining",
        destDescJeju: "Nature, Beaches",

        // Calendar & Search Common
        dateSelect: "Select Date",
        checkIn: "Check-in",
        checkOut: "Check-out",
        btnReset: "Reset",
        btnConfirm: "Confirm",
        
        // Calendar Popup
        calTitle: "Calendar",
        calFlexible: "Flexible",
        calFlexTitle: "How long is your stay?",
        calFlex3: "3 Nights",
        calFlex7: "1 Week",
        calFlex30: "1 Month",
        
        // Guest Popup
        guestRooms: "Rooms",
        guestAdults: "Adults",
        guestAdultsDesc: "Ages 18+",
        guestChildren: "Children",
        guestChildrenDesc: "Ages 0-17",
        
        // Hotel Destination Descriptions
        descShoppingDining: "Shopping, Dining",
        descShoppingSightseeing: "Shopping, Sightseeing",
        descSightseeingBeach: "Sightseeing, Beach",
        descBeachResort: "Beach, Resort",
        descSnowBeer: "Snow, Beer",
        descNightModern: "Night View, Modern",
        descEuropeBeer: "European Style, Beer",
        descArtRomantic: "Art, Romantic",
        descHistoryCulture: "History, Culture",
        descRuinsDining: "Ruins, Dining",
        descArchiPassion: "Architecture, Passion",
        descCityShopping: "City, Shopping",
        descRelaxSurf: "Relaxation, Surfing",
        descNightlife: "Nightlife",
        descFamilyRelax: "Family Relaxation",
        descDivingSea: "Diving, Sea",
        descYogaNature: "Yoga, Nature",
        descCityLuxury: "City, Luxury",

        // Hotel Names & Locations (Static Data)
        hotelNameGrandHyatt: "Grand Hyatt Jeju",
        hotelLocGrandHyatt: "Nohyeong-dong, Jeju City · 5 min walk to beach",
        hotelNameOsakaRitz: "The Ritz-Carlton Osaka",
        hotelLocOsakaRitz: "Kita-ku, Osaka · 3 min walk to Umeda Stn",
        hotelNameDanangInter: "InterContinental Danang Sun Peninsula",
        hotelLocDanangInter: "Son Tra, Da Nang · Private Beach",
        hotelNameBangkokMandarin: "Mandarin Oriental Bangkok",
        hotelLocBangkokMandarin: "Chao Phraya River, Bangkok · River View",
        
        // Hotel Amenities & Review
        amenityWifi: "Free Wifi",
        amenityPool: "Pool",
        amenityBreakfast: "Breakfast Included",
        amenityFitness: "Fitness Center",
        amenitySpa: "Spa",
        amenityInfinity: "Infinity Pool",
        amenityShuttle: "Shuttle Boat",
        reviewExcellent: "Excellent",
        reviewGreat: "Great",
        reviewSuffix: " reviews",
        pricePerNight: "Per Night",
        priceTaxIncl: "Tax Included",
        discountOff: "OFF",

        // Destination Names & Counts
        destNameSeoul: "Seoul",
        destNameIncheon: "Incheon",
        destNameBusan: "Busan",
        destNameSokcho: "Sokcho",
        destNameGyeongju: "Gyeongju",
        destNameFukuoka: "Fukuoka",
        destNameJeju: "Jeju Island",
        destNameOsaka: "Osaka",
        destNameDanang: "Da Nang",
        destNameBangkok: "Bangkok",
        destNameTokyo: "Tokyo",
        destNameSingapore: "Singapore",
        destCountJeju: "3,240 properties",
        destCountOsaka: "5,120 properties",
        destCountDanang: "2,890 properties",
        destCountBangkok: "8,450 properties",
        destCountTokyo: "7,320 properties",
        destCountSingapore: "1,890 properties",
        badgeSpecial: "Special",
        descTourism: "Tourism",
        descBeachDining: "Beach, Dining",
        descCultureReligion: "Culture, Religious Activities",


        // Activity Cards (Static Data)
        actTitleCebu: "[Cebu] Oslob Whale Shark Tour + Canyoneering",
        actLocCebu: "Cebu · Water Sports",
        actTitleBangkok: "[Bangkok] Let's Relax Spa (Select Branch)",
        actLocBangkok: "Bangkok · Massage",
        actTitleVenice: "[Venice] Gondola Ride + Audio Guide",
        actLocVenice: "Venice · Tour",
        actTitleHawaii: "[Waikiki] Surfing Lesson (Korean Instructor)",
        actLocHawaii: "Hawaii · Surfing",
        actBenefitPhoto: "Free Photos",
        actBenefitFast: "Fast Track",

        // Life Page
        lifeHeroSubtitle: "Month-long stays worldwide with Jeju Air,<br><strong>The perfect ecosystem from stay to rental car</strong>",
        lifeSearchSummaryTitle: "Where to live?",
        lifeSearchSummaryDesc: "Select region, dates, and options",
        lifeDestPlaceholder: "Where would you like to live for a month?",
        lifeDestJapanChina: "Japan / China",
        lifeDestSEAsia: "Southeast Asia",
        lifeDestEurope: "Europe / America",
        
        lifeStayWarning: "* Please select at least 14 nights",
        lifeAmenityLabel: "Essentials",
        lifeAmenityPlaceholder: "Kitchen, Washer, etc.",
        lifeOptKitchen: "Full Kitchen",
        lifeOptWasher: "Washer/Dryer",
        lifeOptDesk: "Work Desk",
        lifeOptParking: "Private Parking",
        lifeSearchBtn: "Search Long Stays",
        
        lifeSynergyTitle: "Jeju Air X Mobility Benefits Worldwide",
        lifeSynergyDesc: "Double Refresh Points on flight bundles + 50% off overseas rental cars!",
        lifeSynergyLink: "View Jeju Universe Benefits",
        
        lifeCurationTitle: "Homes for Your Lifestyle",
        lifeCurationDesc: "Discover curated stays for your month-long journey",
        lifeCurChiangmaiDesc: "Sanctuary for digital nomads,<br>Perfect workspace and low cost of living",
        lifeCurLisbonDesc: "Old alleys and Fado music,<br>Romantic European daily life",
        lifeCurBaliDesc: "Days filled with yoga and meditation,<br>Healing stays with rice paddy views",
        
        lifeMagTag: "Global Pick",
        lifeMagTitle: "Chiang Mai, A Slow Morning<br>for Travelers",
        lifeMagDesc: "Waking up to the ridges of Doi Suthep or the vibrancy of Nimman Haemin.<br>Experience comfort like a 'local' that hotels can't offer.<br>From work at a regular cafe to dinner at the night market,<br>experience the true nomad life.",
        lifeMagLink: "Read More",
        
        lifeInfraTitle: "Convenient Nearby Infrastructure",
        lifeInfraDesc: "Check essential amenities for long stays",
        lifeInfraMart: "Supermarket",
        lifeInfraHosp: "General Hospital",
        lifeInfraBus: "Public Transit",
        lifeInfraWalk10: "10 min walk",
        lifeInfraCar15: "15 min drive",
        lifeInfraWalk5: "5 min walk",
        
        lifeConnectTitle: "Seamless Journey",
        lifeConnectTag: "Jeju Air Exclusive",
        lifeConArr: "Arrival",
        lifeConShuttle: "Shuttle 15m",
        lifeConPick: "Pickup/Move",
        lifeConMove: "Move 35m",
        lifeConCheckin: "Check-in",
        lifeConCheckinDesc: "Door lock PW sent",
        
        lifeDealTitle: "Recommended Long Stays",
        lifeDealDesc: "Special rates for stays of 14 nights or more",
        
        lifeReviewTitle: "Real Reviews",
        lifeReviewDesc: "Vivid records from residents who went first",
        lifeReviewText1: "\"Jogging with a view of Doi Suthep in the morning, focusing on work at a shared office during the day. Chiang Mai life was truly like a dream.\"",

        // Selection Standards
        stdTitle: "Standards for a 'Good Home' Verified by Jeju Stay",
        stdSubtitle: "We selected only those optimized for long-term stays from 2 million accommodations worldwide.",
        stdItem1Title: "Fully Equipped Essentials",
        stdItem1Desc: "We only list 'fully furnished' accommodations where you don't need to buy anything, including kitchenware, washing machines, and high-speed Wi-Fi.",
        stdItem2Title: "24-Hour Safety Verification",
        stdItem2Desc: "Our local partners visit in person to verify if the area is safe and if the building's security system is working.",
        stdItem3Title: "Exclusive Long-Stay Rates",
        stdItem3Desc: "We guarantee exclusive 'Long-Stay' rates that are 25-40% cheaper on average than standard daily rates when booking 14 nights or more.",
        stdItem4Title: "Flexible Cancellation Policy",
        stdItem4Desc: "Prioritizing accommodations that allow flexible cancellation and changes up to 7 days before move-in for long-term travelers with frequent schedule changes.",

        // Long Stay Promos & Membership
        // Long Stay Promos & Membership
        lifeMemTitle: "Long Stay Membership Benefits",
        lifeDailySave: "Save per night",
        lifePerNightMsg: "Approx. per night",
        lifeTotal30: "Total for 30 nights (Tax incl.)",
        lifePerNightAvg: "Avg per night",
        lifeUtilityIncl: "Utilities included",
        lifeMemberDiscount: "Jeju Air Member Discount Applied",
        lifeTaxServiceIncl: "Tax & Service Charge Included",



        promoLuggageTitle: "Extra 10kg<br>Checked Baggage",
        promoLuggageDesc: "No worries about heavy luggage,<br>benefits when flying Jeju Air",
        promoCardTitle: "Local Life<br>Membership Card",
        promoCardDesc: "Up to 20% affiliate discount<br>at local restaurants, cafes, rentals",
        promoGuideTitle: "Month-Long Stay<br>Guidebook",
        promoGuideDesc: "From trash disposal to nearby amenities,<br>essential living info included",


        // Activities Page
        actHeroTitle: "Beyond the Trip,<br>Perfect Connection with Jeju Air",
        actHeroSubtitle: "Local experiences exclusively for passengers",
        actSearchPlaceholder: "Where are you going? Search cities or activities",
        actSearchBtn: "Search",
        
        filterAll: "All",
        filterTour: "Tour/Guide",
        filterTicket: "Tickets",
        filterWater: "Water Sports",
        filterSpa: "Spa/Healing",
        filterFood: "Food/Dining",

        authTitle: "Jeju Air Passenger Auth",
        authDesc: "Verify your ticket and get <strong>up to 50% extra discount</strong>.",
        authBtn: "Verify & Get Benefits",
        
        authModalTitle: "Jeju Air Boarding Pass Auth",
        authModalDesc: "Enter booking ref (6 digits) and boarding date.",
        authLabelRes: "Booking Ref",
        authLabelDate: "Date",
        authSubmit: "Apply Benefit",
        
        actSectionTitle: "Recommended Activities",
        actInstant: "Instant Confirmation",
        actBenefit: "Jeju Universe Benefit",
        actPoint2x: "2x Points",

        // Customer Center
        csHeroTitle: "How can we help you?",
        csHeroSubtitle: "Search for your questions or check the FAQs below.",
        csSearchPlaceholder: "Enter keywords (e.g., Baggage, Refund, Change)",
        csTabAll: "FAQ",
        csTabRes: "Flight Booking",
        csTabHotel: "Hotel/Stay",
        csTabBaggage: "Baggage",
        csTabMembership: "Membership",
        
        faqCatRes: "[Flight]",
        faqQ1: "What are the fees for changing or canceling a reservation?",
        faqA1: "Fees depend on the fare rules of your ticket. Special fares may be non-refundable or incur high fees. Check exact fees in [My Page > Booking].",
        
        faqCatBag: "[Baggage]",
        faqQ2: "What is the free checked baggage allowance?",
        faqA2: "For international flights: FLY 15kg, FLYBAG 15kg, BIZ LITE 30kg. Carry-on is limited to 1 bag under 10kg. (May vary by route and member tier.)",
        
        faqCatMem: "[Membership]",
        faqQ3: "When do Refresh Points expire?",
        faqA3: "Points are valid for 3 years from accumulation. Event points may have different validity. Check in [My Page > Points].",
        
        faqCatHotel: "[Hotel]",
        faqQ4: "Can I use points for hotel bookings?",
        faqA4: "Yes, you can use Refresh Points like cash when booking Jeju Stay partner hotels. 1 Point = 1 KRW.",
        
        faqQ5: "What is the policy for pregnant passengers?",
        faqA5: "Under 32 weeks: No restrictions. 32-36 weeks: Doctor's note required. Over 37 weeks (33 for multiples): Boarding may be restricted.",

        inquiryTitle: "Still have questions?",
        inquiryDesc: "Our AI Chatbot is available 24/7 to answer your questions quickly.",
        inquiryBtn: "1:1 Chat Inquiry",

        // Long Stay Card Labels (Missing keys added)
        lifeDailySave: "Save per night",
        lifePerNightMsg: "Approx. per night",
        lifeTotal30: "Total for 30 nights (Tax incl.)",
        lifePerNightAvg: "Avg per night",
        lifeUtilityIncl: "Utilities included",
        lifeMemberDiscount: "Jeju Air Member Discount Applied",
        lifeTaxServiceIncl: "Tax & Service Charge Included"
    }
};
